### ISSUE TITLE
Confusing documentation for resource-based policies

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/amazon-cloudwatch-logs-user-guide#16]
As far as I understand it, CloudWatch Logs supports _two_ different kinds of resource-based policies: policies on an entire account's set of log groups, described by `DescribeResourcePolicies`, and policies on individual log destinations, described by `DescribeDestinations`.

Now, [this documentation page on CWL access control](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/iam-access-control-overview-cwl.html#identity-based-policies-cwl) is a bit confusing. When it talks about resource-based policies, it only mentions the ones attached to log destinations, and I can't see any mention of the "top-level policies" anywhere.

Furthermore, the sample policy listed under the "Identity-Based Policies" heading actually appears to be a "top-level" resource-based policy of the sort I described above. You can tell because it has a `Principal` element, which wouldn't be valid when attached to an IAM principal.

I might have missed some documentation on the top-level resource-based policies but the only mention I can find of them anywhere is in relation to their use by route53 DNS logs, which doesn't seem ideal. Can this stuff be documented a little more clearly and centrally? It would be interesting to see some examples of AWS services other than route53 that can use it, or other non-service usages of those policies.

**Comment by copumpkin** [comment]
From what I can see, those resource-based policies don't actually allow cross-account access, right? In theory I can write a principal from another account into one and it accepts it, but the `PutLogEvents` API doesn't seem to let me send my logs across accounts. I might be missing something, but it would be good to specify things like that in the documentation too 😄

**Comment by copumpkin** [comment]
@chrisdr just wanted to make sure you saw this, since this repo is a bit quiet 😄

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
