### ISSUE TITLE
S3ExportTasksConsole.md need to add s3:PutObjectACL for SendingAccount 

### ISSUE THREAD

**Issue by lindahu1** [awsdocs/amazon-cloudwatch-logs-user-guide#17]
Need to  add `s3:PutObjectACL` for SendingAccount or I will get the error in ap-northeast-1, even I already have `s3:PutObject`.
```
"errorMessage": "Please ensure that the CreateExportTask caller has been granted s3:PutObject access to the bucket.",
```

* If the bucket is in a different account, use the following policy instead. It includes an additional statement using the IAM user you created in the previous step.
```
{
    "Version": "2012-10-17",
    "Statement": [
      {
          "Action": "s3:GetBucketAcl",
          "Effect": "Allow",
          "Resource": "arn:aws:s3:::my-exported-logs",
          "Principal": { "Service": "logs.us-west-2.amazonaws.com" }
      },
      {
          "Action": "s3:PutObject" ,
          "Effect": "Allow",
          "Resource": "arn:aws:s3:::my-exported-logs/random-string/*",
          "Condition": { "StringEquals": { "s3:x-amz-acl": "bucket-owner-full-control" } },
          "Principal": { "Service": "logs.us-west-2.amazonaws.com" }
      },
      {
          "Action": ["s3:PutObject","s3:PutObjectAcl"] ,
          "Effect": "Allow",
          "Resource": "arn:aws:s3:::my-exported-logs/random-string/*",
          "Condition": { "StringEquals": { "s3:x-amz-acl": "bucket-owner-full-control" } },
          "Principal": { "AWS": "arn:aws:iam::SendingAccountID:user/CWLExportUser" }
      }
    ]
}
```

**Comment by giovannifl** [comment]
Does above approach also work if this activity is executed between the CloudWatch group and the S3 bucket are in two complete;y different organizations ?

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
