### ISSUE TITLE
Invalid JSON in example

### ISSUE THREAD

**Issue by morganchristiansson** [awsdocs/amazon-cloudwatch-logs-user-guide#2]
https://github.com/awsdocs/amazon-cloudwatch-logs-user-guide/blob/master/doc_source/iam-access-control-overview-cwl.md#identity-based-policies-iam-policies

.Statement.Action array is not closed

**Comment by chrisdr** [comment]
You are correct- thanks!   I will include this in the update I am planning to upload soon.
