### ISSUE TITLE
Example returns "Invalid filter pattern"

### ISSUE THREAD

**Issue by sd65** [awsdocs/amazon-cloudwatch-logs-user-guide#21]
Hi,

In the Cloudwatch Logs Documentation, Filter and Pattern Syntax :
https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html
(https://github.com/awsdocs/amazon-cloudwatch-logs-user-guide/blob/abb2f62b5c1ba7a87e1193647554d7f2dcb06a50/doc_source/FilterAndPatternSyntax.md)

One can see the example :
`[ip, user, username, timestamp, request, status_code = 4* && bytes > 1000]`

Or pasting this as is in the Cloudwatch Logs Filter results in a : "Invalid filter pattern".
Is the documentation incorrect or is this a regression ?

Regards

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
