### ISSUE TITLE
Using dash "-" in a field name triggers error trying to 'parse' a @message

### ISSUE THREAD

**Issue by bugre** [awsdocs/amazon-cloudwatch-logs-user-guide#22]
Is this a known / expected behaviour ? 

I'm trying to parse some logs, and some filed names had dash ("-") between their names, like 'host-name'  and that triggers a parsing "We are having trouble understanding the query." error.

Replacing the "-" by "_" or removing it, solves the problem.

### works fine:
`fields @timestamp, @message
| parse @message "name=*, ip=*, *" as host_name, ip, rest 
| limit 10
`
### error "understanding the query.."
`fields @timestamp, @message
| parse @message "name=*, ip=*, *" as host-name, ip, rest 
| limit 10
`
### working
![image](https://user-images.githubusercontent.com/6900672/65173317-e8261b00-da24-11e9-8c58-dd302aa20676.png)

### failing
![image](https://user-images.githubusercontent.com/6900672/65172898-2d961880-da24-11e9-9191-341ed6b9fb0c.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
