### ISSUE TITLE
Encryption at rest unclear

### ISSUE THREAD

**Issue by Barker404** [awsdocs/amazon-cloudwatch-logs-user-guide#3]
In ["What is Amazon Cloudwatch Logs"](https://github.com/awsdocs/amazon-cloudwatch-logs-user-guide/blob/e8e431c04ca2733b2ebaf396c6a71ecf8ed49130/doc_source/WhatIsCloudWatchLogs.md), the first bullet point mentions that "Log data is encrypted while in transit and while it is at rest". However, I was surprised that this never comes up anywhere else in the documentation (or even the FAQ). In particular, the page on KMS encryption of logs gives the impression that logs are unencrypted by default.

Are you able to confirm that this sentence is accurate? If it is, I think it would be helpful to make this more clear and mentioned in the other relevant locations.

**Comment by chrisdr** [comment]
I have confirmed that it is accurate, however the service team does not have more details about that encryption that it can make public at this time.
