### ISSUE TITLE
Docs Out of Sync with Public documentation

### ISSUE THREAD

**Issue by jvelliott** [awsdocs/amazon-cloudwatch-logs-user-guide#37]
Noticed a mismatch in the limit on the number of Subscription Filters allowed between

https://github.com/awsdocs/amazon-cloudwatch-logs-user-guide/blob/master/doc_source/cloudwatch_limits_cwl.md

and 

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/cloudwatch_limits_cwl.html

With the latter appearing to be correct.

I assume there could be other things that are out of sync as well.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
