### ISSUE TITLE
Docs - CloudWatch Logs: Missing Regions?

### ISSUE THREAD

**Issue by Sean12697** [awsdocs/amazon-cloudwatch-logs-user-guide#39]
I'm looking at the [QuickStartEC2Instance.md](https://github.com/awsdocs/amazon-cloudwatch-logs-user-guide/blob/master/doc_source/QuickStartEC2Instance.md) documentation, specifically the following line and table (below the note, which doesn't seem to exist in the Markdown file but does on [docs.aws.amazon.com](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartEC2Instance.html)):

> You can install the CloudWatch Logs agent by specifying the us-east-1, us-west-1, us-west-2, ap-south-1, ap-northeast-2, ap-southeast-1, ap-southeast-2, ap-northeast-1, eu-central-1, eu-west-1, or sa-east-1 regions.

This seems to conflict with the listed [CloudWatch Logs endpoints](https://docs.aws.amazon.com/general/latest/gr/cwl_region.html) and [Amazon CloudWatch endpoints](https://docs.aws.amazon.com/general/latest/gr/cw_region.html), for example `eu-west-2` seems to be a valid region endpoint, although it is not listed in this specific quick start documentation (where only `eu-west-1` exists in Europe).

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
