### ISSUE TITLE
Docs - Confusing Breadcrumbs in CloudWatch and Cloudwatch Logs

### ISSUE THREAD

**Issue by yu-tomori** [awsdocs/amazon-cloudwatch-logs-user-guide#50]
I was confused by the same display of the breadcrumbs in `CloudWatch` docs and it in `CloudWatch Logs` in docs.

The breadcrumbs in `CloudWatch Logs` should be like `AWS > Documentation > Amazon CloudWatch Logs`, I think.

![スクリーンショット 2022-09-05 16 18 53](https://user-images.githubusercontent.com/39375351/188391601-23b0e1f8-f072-434e-a7e9-ef98a0b9aeca.png)
![スクリーンショット 2022-09-05 16 18 35](https://user-images.githubusercontent.com/39375351/188391621-36223096-0f75-44fa-8b3e-cc0883674514.png)

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
