### ISSUE TITLE
Encrypting CloudWatch logs, KMS resource permissions, Best practice

### ISSUE THREAD

**Issue by mtrampic** [awsdocs/amazon-cloudwatch-logs-user-guide#53]
Hi there, 

Reading AWS documentation for CW permissions needed, to have log group encrypted. I can see that in KMS resource policy permissions are specified with wildcard (*).
Is this really necessary and following best practices ? 

To rephrase Question into suggestion, what would be useful is to have example resource policy following AWS Security best practices and standards.

```
{
            "Effect": "Allow",
            "Principal": {
                "Service": "logs.region.amazonaws.com"
            },
            "Action": [
                "kms:Encrypt*",
                "kms:Decrypt*",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*",
                "kms:Describe*"
            ],
            "Resource": "*",
            "Condition": {
                "ArnLike": {
                    "kms:EncryptionContext:aws:logs:arn": "arn:aws:logs:REGION:ACCOUNT-ID:log-
group:LOG-GROUP-NAME"
                }
            }
        }
```

**Comment by mtrampic** [comment]
Other developers take it downstream and use in their development of policies.
https://github.com/search?q=org%3Aaws-samples%20kms%3AEncryptionContext%3Aaws%3Alogs%3Aarn%20language%3Ayaml%20&type=code

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
