### ISSUE TITLE
This repository is not the source of truth

### ISSUE THREAD

**Issue by galaxy4public** [awsdocs/amazon-cloudwatch-logs-user-guide#6]
Right now there is a discrepancy between the content inside this repository and what is published on https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html .  The official documentation is richer which means that this repository is not authoritative.  For example, the official documentation has a much better section on "OR Pattern Matching" for "Matching Terms in Log Events".

**Comment by chrisdr** [comment]
Sorry, we are new to publishing the docs to Github and do not have an automated process to do so, I have to do it manually.  I will keep fine tuning my update schedule until I find a balance of keeping this repository fresh, and the amount of time spent on manual updates.  I will update this repository now.
